defaults: &defaults
  docker:
    - image: circleci/node:10

node_key: &node_key
  key: node-{{ checksum "package.json" }}

restore_node: &restore_node
  - restore_cache:
      <<: *node_key

save_node: &save_node
  - save_cache:
      <<: *node_key
      paths:
        - node_modules

deploy_static: &deploy_static
  <<: *defaults
  steps:
    - checkout
    - <<: *restore_node
    - run:
        name: install aws
        command: |
          sudo apt-get -y -qq update
          sudo apt-get -y -qq install python3.4-dev
          curl -O https://bootstrap.pypa.io/get-pip.py
          python3.4 get-pip.py --user
          export PATH=~/.local/bin:$PATH
          pip install awscli --upgrade --user

    - deploy:
        name: Upload to S3
        command: |
          export PATH=~/.local/bin:$PATH
          env | sed -n "s/^${ENV}_//p" > .env
          export $(<.env)
          npm run build

          sed -ri 's/\[(-?[0-9]{2})\.([0-9]{6})[0-9]*,(-?[0-9]{2})\.([0-9]{6})[0-9]*\]/\[\1\.\2,\3\.\4\]/g' dist/data/districts.geojson
          sed -ri 's/,?"shape_area":"-?[0-9]*\.?[0-9]*",?"shape_leng":"-?[0-9]*\.?[0-9]*"//g' dist/data/districts.geojson
          gzip -9 dist/data/districts.geojson

          aws s3 sync ./dist/ s3://$AWS_BUCKET/$AWS_S3_KEY --acl public-read --cache-control max-age=3600
          aws s3 cp ./dist/index.html s3://$AWS_BUCKET/$AWS_S3_KEY/index.html --acl public-read --cache-control max-age=0
          aws s3 cp ./dist/data/districts.geojson.gz s3://$AWS_BUCKET/$AWS_S3_KEY/data/districts.geojson --acl public-read --cache-control max-age=0 --content-type "application/javascript" --content-encoding "gzip"
          aws cloudfront create-invalidation --distribution-id $AWS_CLOUDFRONT --paths "/voter-guide/*"

version: 2

jobs:
  build-static:
    <<: *defaults

    steps:
      - checkout

      - <<: *restore_node
      - run:
          name: install node deps
          command: |
            if [ ! -d node_modules ]; then
              npm ci
            fi
      - <<: *save_node

  deploy-demo:
    environment:
      AWS_BUCKET: gothamist-project-demo
      ENV: DEMO
    <<: *deploy_static

  deploy-prod:
    environment:
      AWS_BUCKET: gothamist-project-prod
      ENV: PROD
    <<: *deploy_static

workflows:
  version: 2

  deploy-demo:
    jobs:
      - build-static:
          filters:
            branches:
              only: master
      - deploy-demo:
          requires:
            - build-static

  deploy-prod:
    jobs:
      - build-static:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+/
      - deploy-demo:
          requires:
            - build-static
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+/
